### ISSUE TITLE
"What's the time" gives time in different timezone

### ISSUE THREAD

**Issue by spagy** [MycroftAI/skill-date-time#56]
When I ask "What's the time", Mycroft is out by 6 hours but when I ask "What's the time in London" I get the right time (I'm in England).

It seems like Mycroft might be defaulting to CDT or something but I'm not really sure. The the timezone is set to 'Europe/London' on the computer Mycroft is running on.

**Comment by penrods** [comment]
Go to home.mycroft.ai and look at your devices.  (https://home.mycroft.ai/#/device)  When you click on the device's card you'll see a Location field.  I'm 99.99% certain that it will be set to the default -- Lawrence, KS.  You just need to change it to "London, UK" or whatever.

If this does the trick. please go ahead and close this issue out.

**Comment by spagy** [comment]
That was exactly it, thanks for your fast reply :)
