### ISSUE TITLE
Installing skill-date-time on Mark 1 fails because of numpy

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/skill-date-time#90]
The installation of skill-date-time on a Mark 1 pulls `timezonefinder` (from `requirements.txt`), which in turn pulls `numpy`. 

My mark 1 tries to download a zip and build numpy from source, failing:

```
pi@mycroft:/opt/mycroft/skills $ msm install mycroft-date-time
/opt/venvs/mycroft-core/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
INFO - building SkillEntry objects for all skills
INFO - Best match (1.0): mycroft-date-time by mycroftai
INFO - Downloading skill: https://github.com/mycroftai/skill-date-time
INFO - Installing system requirements...
INFO - Installing requirements.txt for mycroft-date-time
INFO - Problem performing action. Restoring skill to previous state...
INFO - invalidating skills cache
PipRequirementsException: 
Pip returned code 1:
Collecting timezonefinder
  Using cached timezonefinder-4.4.1-py36.py37.py38-none-any.whl (39.2 MB)
Collecting numpy>=1.16
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /opt/venvs/mycroft-core/bin/python /opt/venvs/mycroft-core/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-58lvcfgg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools<49.2.0' wheel 'Cython>=0.29.21'
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/opt/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/python/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/opt/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/opt/python/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/venvs/mycroft-core/bin/python /opt/venvs/mycroft-core/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-58lvcfgg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools<49.2.0' wheel 'Cython>=0.29.21' Check the logs for full command output.

```

According to mycroft I'm on the latest version (20.08). However, my mark1 still runs on debian jessie (oldoldstable).

Am I doing something wrong? I don't see the option to "show the time when idle" in the mycroft settings page, that's how I found out it was not installed.

**Comment by forslund** [comment]
I know it took time to install the update when needing to install numpy but it should succeed...

If I check my Mark-1 I see this:

```
(mycroft-core) pi@mark_1:~ $ pip show numpy
Name: numpy
Version: 1.19.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /opt/venvs/mycroft-core/lib/python3.7/site-packages
Requires: 
Required-by: timezonefinder
```

So it managed to install that version...will try to update to the exact version that fails for you

**Comment by forslund** [comment]
Hmm, no that minor version difference doesn't seem to be the issue...possibly some other requirement that fails?

Also: Mark-1 is still at Jessie so that's correct. We added a custom built python3.7 so we could continue on a supported python version.

**Comment by zeehio** [comment]
Thanks @forslund. I checked again and I believe I found a solution.

The error I found seemed to be related (from the logs above) to the `typing` module, which is weird that it fails because it should be part of the python standard library. However, I saw in my log above references to `/opt/venvs/mycroft-core/lib/python3.7/site-packages/typing.py` as if the typing package was installed through pip (which should not happen on a python-3.7 venv).

And Bingo! Apparently there is a `typing` package installed, required by my `msk`:

```
(mycroft-core) pi@mycroft:~ $ pip show typing
Name: typing
Version: 3.7.4.3
Summary: Type Hints for Python
Home-page: https://docs.python.org/3/library/typing.html
Author: Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Ivan Levkivskyi
Author-email: jukka.lehtosalo@iki.fi
License: PSF
Location: /opt/venvs/mycroft-core/lib/python3.7/site-packages
Requires: 
Required-by: msk
```

And `msk` (as you probably already know, I didn't :smiley: ) is the mycroft-skills-kit:

```
(mycroft-core) pi@mycroft:~ $ pip show msk
Name: msk
Version: 0.3.15
Summary: Mycroft Skills Kit
Home-page: https://github.com/MycroftAI/mycroft-skills-kit
Author: Mycroft AI
Author-email: support@mycroft.ai
License: Apache-2.0
Location: /opt/venvs/mycroft-core/lib/python3.7/site-packages
Requires: GitPython, typing, msm, pygithub, requests, colorama
Required-by: mycroft-core
```

Fortunately, I've checked the `msk` repository and `msk 0.3.16` is out there and fixes the issue (thanks to https://github.com/MycroftAI/mycroft-skills-kit/commit/0c22d30464f162727bf1b4f50705354e4e9b309f ). I could update it manually (`pip install -U msk`).

However, my `mycroft-core` has a strict dependency on `msk==0.3.15`. I got this warning:

```
mycroft-core 20.8.0 requires msk==0.3.15, but you'll have msk 0.3.16 which is incompatible.
```

I've checked the `mycroft-core` repository and on https://github.com/MycroftAI/mycroft-core/commit/6cb219dc15fc6138f5f7e0cf3489d7f29cb00dd4 the dependency on `msk` was updated, so on the next release the typing dependency will cease to exist. I could uninstall `typing` myself. 

Related Question: When a package stops being required is it automatically removed from the venv?

I tried again building numpy, and I got another error, related to the `uuid` package.

```
(mycroft-core) root@mycroft:/home/pi# pip show uuid
Name: uuid
Version: 1.30
Summary: UUID object and generation functions
Home-page: http://zesty.ca/python/
Author: Ka-Ping Yee
Author-email: ping@zesty.ca
License: UNKNOWN
Location: /opt/venvs/mycroft-core/lib/python3.7/site-packages
Requires: 
Required-by: 
```

This seems another pip package stepping over the python standard library. I don't know how `uuid` got installed in the first place. I am removing it and trying again. The existence of this installed package makes me wonder if the answer to the question above is "No, packages that are not required anymore are not automatically removed".

I'm now building the numpy wheel. If it succeeds (I guess it will) I will try to install the skill again.

I guess doing a `pip uninstall typing uuid` in all mark 1 units after the next upgrade would make sense. I don't know if that would make sense in pycroft or other installations, nor whether to report mark1 issues like this one.

Having a mark1 pip repository with prebuilt wheels for numpy, instead of making all users build numpy would also be nice. numpy does not take as long as the mimic compilation, but it's not fast and it uses all cores, so my mycroft unit is not very responsive in the process :laughing: 

I will close this issue, since this skill is not causing any trouble and I think the issue is solved. As far as I know you are not working for Mycroft anymore, so an extra reason for me to thank you for spending your time testing my issues.

**Comment by forslund** [comment]
If a dependency is removed I think depends on the method of installation. If it was part of the mycroft-core package I think it will be removed as part of the update (since the file belongs to the older deb package), if a skill installs a dependency I think will remain as it's outside of the control of the deb package.

happy to help :)

**Comment by zeehio** [comment]
My mark 1 ran out of memory while installing numpy and the building was killed :-(

Trying again (and leaving it for the night, using tmux) with:

```
pip install --install-option="--jobs=1" numpy
```

Oh, and based on the logs from my previous attempt I decided to `apt-get install libatlas-base-dev`, so the resulting numpy binaries use a good blas and lapack library and are faster.

**Comment by krisgesling** [comment]
Is it worth us adding the `libatlas-base-dev` package to the dependencies anyway? 

Thanks for all the digging into this too!

**Comment by zeehio** [comment]
@krisgesling with respect to the libatlas-base-dev package... The only usage of numpy in the Mycroft stack I am aware of is by the dependency here that takes care of  "finding the timezone given these coordinates". Since this does not seem that expensive, I don't think it makes a big difference to have the atlas library or not. However, if in the future another skill uses numpy a bit more heavily, I guess having an optimized linear algebra library underneath such as libatlas will be beneficial.

I also think that installing libatlas probably reduces the compilation time of numpy, since all the linear algebra functions are already built and installed. I haven't benchmarked anything though.

Overall I think it is worth installing it.

It would be better to upgrade from Jessie to Stretch and to Buster, use the python version from Debian stable and add the https://piwheels.org pip repository, so it offers precompiled packages for all the pypi packages. This would speed up skill updates, especially when something big like numpy appears.

Piwheels precompiles packages for each Debian release, with their respective python version, so the wheels for python 3.7 do not work on Debian Jessie (since piwheels builds for Jessie-python 3.4 or Buster-3.7, but not Jessie-3.7).

Removing the `typing` and `uuid` pip packages in all mark 1 units on the next update (if they are installed) is something you should really take care of. The fact that pip packages that are not required anymore are kept installed may become a maintenance problem long term. The only easy solution I see is to re-create the venv, but that is very time consuming (and risky) on a raspberry pi, without precompiled wheels.

Technical debt on the Mark1 will eventually become a  bill too large to pay. Being on oldoldstable is a concern to me, given that I don't see any migration plan from Mycroft being set in place. I understand there is a lot on your table, but in the end I will not want to have a functional but vulnerable device on my living room with a microphone attached to it.

**Comment by forslund** [comment]
A clean could be performed at regular interval without too much issues. Could be made part of the major release updates.

We discussed the upgrade to buster last year but the work to make that a smooth and safe upgrade on the Mark-1 was deemed too big for the small team. Backporting python3.7 and required packages (openssl for example) was instead decided on.

The thought back then was also that the Mark-1 was closing in on End of Life...

The simplest possibility may be to create a new Mark-1 image using buster, and let it be a manual update switching the SD card...

Edit: but this is of course up to Mycroft to decide.
